### ISSUE TITLE
Change street view link

### ISSUE THREAD

**Issue by 1egoman** [openhacksyr/openhacksyr.github.io#16]
Doesn't really point at the sign. Something like this? https://www.google.com/maps/@43.0470467,-76.1505448,3a,75y,44.84h,74.92t/data=!3m6!1e1!3m4!1sCM6fQAord-wjakpEAWCD8Q!2e0!7i13312!8i6656

(on this page: http://openhacksyr.com/faq/)

**Comment by vormwald** [comment]
Pull Requests welcome! :)

**Comment by myrridin** [comment]
https://github.com/openhacksyr/openhacksyr.github.io/pull/17
